### ISSUE TITLE
他怎么提示这个错误

### ISSUE THREAD

**Issue by swanghao** [ttop5/ks-unlimited-marquee#3]
Module not found: Error: Can't resolve './style.css' in 'E:\react\DT2WEB\node_modules\ks-unlimited-marquee\es'

**Comment by ttop5** [comment]
你本机依赖，安装一下就好了

**Comment by swanghao** [comment]
npm install ks-unlimited-marquee 已经安装了 在使用的时候提示这个错误

**Comment by ttop5** [comment]
你检查一下是否安装上了，还有就是路径有没有问题

**Comment by swanghao** [comment]
node_modules文件夹下已经有ks-unlimited-marquee这个文件夹，我参照Usage使用方法 他就提示这个错误

**Comment by swanghao** [comment]
styel.css这个文件我应该不需要引用的是吧

**Comment by ttop5** [comment]
是的

**Comment by swanghao** [comment]
E:/react/DT2WEB/~/ks-unlimited-marquee/es/index.js 11:0-21他错误是这个位置

**Comment by swanghao** [comment]
他下面貌似是没有style.css文件

**Comment by swanghao** [comment]
我把ks-unlimited-marquee\es下面的index文件里面import ‘./style.css’改成了import '../src/style.css';就好了

**Comment by ttop5** [comment]
嗯，感谢反馈

**Comment by swanghao** [comment]
ks-unlimited-marquee\es下面的index文件里面import ‘./style.css’你那边能改成了import '../src/style.css';或者添加一个style.css文件好吗？我重新安装下

**Comment by ttop5** [comment]
好的

**Comment by swanghao** [comment]
现在方便更新下吗？我等着用这个插件

**Comment by ttop5** [comment]
我刚更新了，你试一下哈

**Comment by swanghao** [comment]
Module parse failed: E:\react\DT2WEB\node_modules\ks-unlimited-marquee\src\index.js Unexpected token (6:19)
You may need an appropriate loader to handle this file type.
| 
| class UnlimitedMarquee extends Component {
|   static propTypes = {
|     content: PropTypes.node.isRequired,
|     gap: PropTypes.number,

**Comment by ttop5** [comment]
这些loader你的程序里安装了么

**Comment by swanghao** [comment]
npm install ks-unlimited-marquee 不是一起安装吗？

**Comment by swanghao** [comment]
在原先的基础上添加一个style.css文件或者import路径修改下这样可以吗？

**Comment by swanghao** [comment]
要装哪些loader程序？

**Comment by ttop5** [comment]
项目里用到什么依赖就装什么

**Comment by swanghao** [comment]
依赖应该都是装好的
